// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "2c751f5b99ab6449c2d8090fdddd7943ad33fbf8f8821d42a72df5618498bef3")
